baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Now UI Kit"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "../docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Landing"
    url = "/landing"
    pre = "<i class='now-ui-icons business_bank'></i>"
    weight = 1
[[menu.main]]
    name = "Profile"
    url = "/profile"
    pre = "<i class='now-ui-icons users_single-02'></i>"
    weight = 2
[[menu.main]]
    name = "Signup"
    pre = "<i class='now-ui-icons clothes_tie-bow'></i>"
    url = "/login"
    weight = 3
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CreativeTim"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/CreativeTim"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    background = "https://climate.nasa.gov/system/internal_resources/details/original/417_1263_banner-science-1600x500.jpg"
    name =  ""
    twitter =  ""
    github =  ""
    email =  ""
#    custom_css = []
#    repo = ""
#    branch = "master"
#    math = true

    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    

